#!/usr/bin/env php
<?php
require 'bootstrap.php';

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Symfony\Component\Console\Application;
use Weeks\CurrencyWatcher\Application\Command\FetchCommand;

$console = new Application(
        'Currency Watcher',
        '1.0'
);

$console->setHelperSet(ConsoleRunner::createHelperSet($app->getContainer()->get(EntityManager::class)));
ConsoleRunner::addCommands($console);

$fetch = new FetchCommand(
    $app->getContainer(),
    'fetch'
);

$console->add($fetch);

$console->run();