Weeks\CurrencyWatcher\Domain\Entity\Currency:
    type: entity
    repositoryClass: Weeks\CurrencyWatcher\Application\Repository\DoctrineCurrencyRepository
    table: currencies
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            unique: true
        symbol:
            type: string
        countryName:
            type: string